# -*- coding: utf-8 -*-
"""practise6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBhqnaDb3NNFdtq8Fcp_DnjpXYafbVzX
"""

#from google.colab import files
#uploaded = files.upload()
file1 = open("hotels.txt")
file2 = open("reviews.txt")
hotels = file1.read()
hotels1 = hotels.splitlines()
reviews = file2.read()
reviews1 = reviews.splitlines()

dict1 = {}
list1=[]
for line in reviews1:
  line = line.strip()
  review = line.split("\t")
  
  
  if review[1] in dict1:
    dict1[review[1]] += [review[2]]
  else:
    dict1[review[1]]=[review[2]]
  list1.append(review[0])

dict2 ={}
for line in hotels1:
  hotel = line.split("\t")
  dict2[hotel[0]]=hotel[1]

dict3 = {}
for k,v in dict1.items():
  a = 0
  for x in v:
    a += int(x) 
  a = a/len(v)
  dict3[k] = a

dict4 = {}
for x in list1:
  if x in dict4:
    dict4[x] += 1
  else:
    dict4[x] = 1
maxY = max(dict4.values())
def checkwho(dict):
  for k,v in dict.items():
    if v == maxY:
      return k
maxX = max(dict3.values())
def checkbest(dict):
  for k,v in dict.items():
    if v == maxX:
      return k
def checkbest2(str,dict):
  for k,v in dict.items():
    if k == str:
      return v
def checkhotel(str,dict2,dict3):
  ID = ""
  name = 0.0
  for k,v in dict2.items():
    if str == v:
      ID = k
  for k,v in dict3.items():
    if ID == k:
      name = v
  return name
print("The user who posted the most reviews is "+checkwho(dict4))
print("The best hotel: "+checkbest2(checkbest(dict3),dict2))
print()
boolean1 = True
while boolean1:
  a = input("Please enter a hotel name: ")
  if a == "quit":
    boolean1 = False
    break
  if not a in dict2.values():
    print("Hotel name does not exist in the database.")
  elif  checkhotel(a,dict2,dict3) == 0.0:
    print("Nobody has rated for this hotel yet.")
  else:
    print("The average rating of the hotel: "+str("%.1f" % checkhotel(a,dict2,dict3)))